name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        env:
          BUILD_VERSION: ${{ github.run_number }}
          BUILD_NUMBER: ${{ github.run_number }}
        with:
          arguments: jar

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: Punishments Jar
          path: build/libs/*.jar